Vagrant.require_version ">= 1.5"

Vagrant.configure("2") do |config|
    config.vm.define :loadbalancer do |loadbalancer|
        loadbalancer.vm.provider :virtualbox do |v|
            v.name = "loadbalancer"
            v.customize [
                "modifyvm", :id,
                "--name", "loadbalancer",
                "--memory", 512,
                "--natdnshostresolver1", "on",
                "--cpus", 1,
            ]
        end

        loadbalancer.vm.box = "hashicorp/bionic64"
        loadbalancer.vm.box_version = "1.0.282"
        loadbalancer.vm.network :private_network, ip: "192.168.56.10"
        loadbalancer.vm.network "forwarded_port", guest: 80, host: 8080
        loadbalancer.ssh.forward_agent = true
    end

    (1..3).each do |i|
        config.vm.define "app_#{i}" do |app|
            app.vm.provider :virtualbox do |v|
                v.name = "app_#{i}"
                v.customize [
                    "modifyvm", :id,
                    "--name", "app_#{i}",
                    "--memory", 512,
                    "--natdnshostresolver1", "on",
                    "--cpus", 1,
                ]
            end
    
            app.vm.box = "hashicorp/bionic64"
            app.vm.box_version = "1.0.282"
            app.vm.network :private_network, ip: "192.168.56.1#{i}"
            app.ssh.forward_agent = true
        end
    end
end
