---
- name: install and configure nginx on loadbalancer node
  hosts: loadbalancer
  become: true
  roles:
    - nginx

- name: "install docker and docker Python SDK on all app nodes"
  hosts: app
  become: true
  roles:
    - docker

- name: "pull and run {{ dockerhub_id }}/{{ app_name }} image from DockerHub"
  hosts: app
  roles:
    - deploy
  vars:
    dockerhub_id: sh3b0
    app_name: app_nodejs # specify app_nodejs or app_python

# - name: "Wipe application"
#   hosts: app
#   become: true
#   roles:
#     - wipe
